# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e994feba9b0017e01240288a762ee5e6a74bd3f342f16e177d1e255e589008dde153dbca909ddcb9424d6627fd56318037b8ef8f7024182d49ace9325b70572c

test:
  secret_key_base: 1a06215a4e6e46ac82b5637b6674856e854eb4ce53ec87b6cf8a41fc9060984549135deb9e9bb35fd7baa147e130bd4e8965433b35d93b20f20ed551c1c84f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
